(function(){
'use strict';
const auth=window.profileAuth, db=window.profileDb;
const $=id=>document.getElementById(id);
let currentUser=null, profile=null;
function defaultAvatar(name='OS'){const label=String(name||'OS').slice(0,2).toUpperCase();return 'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="160" height="160"><defs><filter id="glow" x="-50%" y="-50%" width="200%" height="200%"><feGaussianBlur stdDeviation="4" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><rect width="160" height="160" rx="80" fill="#08131c"/><circle cx="80" cy="80" r="58" fill="#39ff6a" opacity=".22"/><text x="80" y="92" text-anchor="middle" font-family="Arial" font-size="46" font-weight="700" fill="#39ff6a" filter="url(#glow)">${label}</text></svg>`)}
function status(msg,error=false){const e=$('profile-status');e.textContent=msg;e.classList.toggle('error',error)}
function photoData(file){return new Promise(resolve=>{if(!file){resolve('');return}const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const max=512,scale=Math.min(1,max/img.width,max/img.height),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.82))};img.onerror=()=>resolve('');img.src=reader.result};reader.onerror=()=>resolve('');reader.readAsDataURL(file)})}
async function load(){auth.onAuthStateChanged(async user=>{currentUser=user||null;if(!user){$('profile-loading').style.display='none';$('profile-content').style.display='none';$('profile-login-needed').style.display='block';return}try{const snap=await db.collection('users').doc(user.uid).get();profile=snap.exists?(snap.data()||{}):{};const name=profile.displayName||user.displayName||String(user.email||'usuario').split('@')[0];$('profile-loading').style.display='none';$('profile-login-needed').style.display='none';$('profile-content').style.display='block';$('profile-avatar').src=profile.photoURL||user.photoURL||defaultAvatar(name);$('profile-name-title').textContent=name;$('profile-email').textContent=user.email||'';}catch(e){$('profile-loading').textContent='No se pudo cargar tu perfil.';console.error(e)}})}
$('back-to-sotano').addEventListener('click',e=>{e.preventDefault();document.body.classList.add('leaving-profile');setTimeout(()=>{window.location.href='index.html'},420)});
$('photo-input').addEventListener('change',async e=>{const file=e.target.files&&e.target.files[0];if(!file)return;if(!file.type.startsWith('image/')||file.size>8*1024*1024){status('La foto debe ser una imagen de menos de 8 MB.',true);return}status('Guardando foto…');try{const photoURL=await photoData(file);if(!photoURL)throw Error('photo');await db.collection('users').doc(currentUser.uid).set({photoURL,updatedAt:Date.now()},{merge:true});await db.collection('livechat').doc('profile_'+currentUser.uid).set({uid:currentUser.uid,photoURL,updatedAt:Date.now()},{merge:true});$('profile-avatar').src=photoURL;profile={...profile,photoURL};status('Foto guardada correctamente.')}catch(err){console.error(err);status('No se pudo guardar la foto.',true)}finally{e.target.value=''}});
$('password-form').addEventListener('submit',async e=>{e.preventDefault();if(!currentUser)return;const old=$('current-password').value,newPass=$('new-password').value;if(newPass.length<6){status('La nueva contraseña debe tener al menos 6 caracteres.',true);return}const btn=e.submitter;btn.disabled=true;try{const cred=firebase.auth.EmailAuthProvider.credential(currentUser.email,old);await currentUser.reauthenticateWithCredential(cred);await currentUser.updatePassword(newPass);$('current-password').value='';$('new-password').value='';status('Contraseña actualizada correctamente.')}catch(err){console.error(err);const code=String(err.code||'');status(code.includes('wrong-password')||code.includes('invalid-credential')?'La contraseña actual no es correcta.':code.includes('requires-recent-login')?'Vuelve a iniciar sesión por seguridad.':'No se pudo cambiar la contraseña.',true)}finally{btn.disabled=false}});
$('logout-button').addEventListener('click',async()=>{document.body.classList.add('leaving-profile');await auth.signOut();setTimeout(()=>{window.location.href='index.html'},420)});
load();
})();
